const C=()=>window.AC_BUYER_CATALOG||[];
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[m]));
const hash=s=>[...String(s||'')].reduce((a,c)=>((a*31+c.charCodeAt(0))>>>0),7);
function photoUrl(item){
  if(item?.image)return item.image;
  const q=encodeURIComponent(`${item?.name||''} ${item?.category||''} indian handicraft product`.toLowerCase().replace(/[^a-z0-9 ]+/g,' ').trim());
  return `https://loremflickr.com/800/600/${q}?lock=${hash(item?.id||item?.name)%10000}`;
}
function fixedPrice(range){const nums=String(range||'').match(/\d[\d,]*/g)?.map(n=>Number(n.replace(/,/g,'')))||[];if(!nums.length)return'₹0';const n=nums.length>1?Math.round((nums[0]+nums[1])/2):nums[0];return`₹${n.toLocaleString('en-IN')}`}
function imageBlock(item,cls='ac-catalog-art'){
  const src=photoUrl(item);
  return `<div class="${cls}"><img src="${esc(src)}" alt="${esc(item.name)}" loading="lazy" decoding="async" referrerpolicy="no-referrer" onerror="this.onerror=null;this.src='https://loremflickr.com/800/600/indian,handicraft?lock=${hash(item?.id||item?.name)%10000}'"></div>`;
}
function setPreference(item){let b={};try{b=JSON.parse(localStorage.getItem('ac-buyer-details')||'{}')}catch{}b.preference=item.type||item.category;localStorage.setItem('ac-buyer-details',JSON.stringify(b));location.reload()}
function productModal(item){document.querySelector('#ac-product-modal')?.remove();const m=document.createElement('div');m.id='ac-product-modal';m.className='modal-backdrop';m.innerHTML=`<div class="login-modal ac-product-modal"><button class="modal-close">×</button>${imageBlock(item,'ac-product-hero')}<span class="eyebrow">${esc(item.category)}</span><h2>${esc(item.name)}</h2><p>${esc(item.type)}</p><strong class="ac-modal-price">${fixedPrice(item.price)}</strong><small>Fixed demo price</small><button class="btn primary ac-use-pref">Use as preference →</button></div>`;document.body.appendChild(m);m.querySelector('.modal-close').onclick=()=>m.remove();m.querySelector('.ac-use-pref').onclick=()=>setPreference(item);m.onmousedown=e=>{if(e.target===m)m.remove()}}
function renderBrowse(){const host=document.querySelector('.dashboard-content');if(!host)return;document.querySelectorAll('.dashboard-sidebar button').forEach(x=>x.classList.remove('active'));document.querySelector('#ac-browse-nav')?.classList.add('active');const cats=['All',...new Set(C().map(x=>x.category))];host.innerHTML=`<section class="workspace-panel ac-browse"><div class="workspace-heading"><div><span class="eyebrow">MARKETPLACE</span><h1>Browse handmade products.</h1><p>Search ${C().length} products from the uploaded catalogs by name, type or category.</p></div><div class="ac-count"><strong>${C().length}</strong><span>products</span></div></div><input id="ac-search" class="shop-search" placeholder="Search products…"/><div id="ac-cats" class="ac-cat-chips"></div><div id="ac-grid" class="ac-catalog-grid"></div></section>`;const search=host.querySelector('#ac-search'),chips=host.querySelector('#ac-cats'),grid=host.querySelector('#ac-grid');let cat='All';function drawCats(){chips.innerHTML=cats.map(c=>`<button type="button" data-c="${esc(c)}" class="${c===cat?'selected':''}">${esc(c)}</button>`).join('');chips.querySelectorAll('button').forEach(b=>b.onclick=()=>{cat=b.dataset.c;drawCats();draw()})}function draw(){const q=search.value.trim().toLowerCase(),list=C().filter(x=>(cat==='All'||x.category===cat)&&(!q||`${x.name} ${x.type} ${x.category}`.toLowerCase().includes(q)));grid.innerHTML=list.map(x=>`<article class="ac-catalog-card" data-product-id="${esc(x.id)}">${imageBlock(x)}<div class="ac-catalog-body"><small>${esc(x.type)}</small><b>${esc(x.name)}</b><strong>${fixedPrice(x.price)}</strong><small class="ac-fixed-note">Fixed price · product photo</small><div class="ac-card-actions"><button data-view="${esc(x.id)}">View →</button><button class="primary-mini" data-pref="${esc(x.id)}">＋ Use as preference</button></div></div></article>`).join('');grid.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>productModal(C().find(x=>x.id===b.dataset.view)));grid.querySelectorAll('[data-pref]').forEach(b=>b.onclick=()=>setPreference(C().find(x=>x.id===b.dataset.pref)))}search.oninput=draw;drawCats();draw()}
function installBrowse(){if(localStorage.getItem('ac-user-role')!=='buyer')return false;const side=document.querySelector('.dashboard-sidebar');if(!side)return false;if(side.querySelector('#ac-browse-nav'))return true;const logout=side.querySelector('.sidebar-logout'),b=document.createElement('button');b.id='ac-browse-nav';b.innerHTML='Browse products <span>→</span>';b.onclick=renderBrowse;side.insertBefore(b,logout||null);return true}
const s=document.createElement('style');s.textContent=`.ac-count{min-width:90px;padding:12px;border-radius:16px;background:rgba(188,82,43,.08);text-align:center}.ac-count strong{display:block;font:700 28px Georgia,serif;color:var(--rust)}.ac-count span{font-size:11px;text-transform:uppercase}.ac-cat-chips{display:flex;gap:8px;flex-wrap:wrap;margin:12px 0 18px}.ac-cat-chips button{border:1px solid rgba(92,53,33,.18);background:#fffaf2;color:var(--espresso);padding:8px 11px;border-radius:999px;font-size:12px;font-weight:700;cursor:pointer}.ac-cat-chips button.selected{background:var(--rust);color:#fff;border-color:var(--rust)}.ac-catalog-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:16px}.ac-catalog-card{overflow:hidden;border:1px solid rgba(92,53,33,.12);border-radius:18px;background:#fffaf2}.ac-catalog-art,.ac-product-hero{position:relative;overflow:hidden;background:#ead3bd}.ac-catalog-art{height:180px}.ac-product-hero{height:220px;border-radius:15px;margin-bottom:14px}.ac-catalog-art img,.ac-product-hero img{width:100%;height:100%;object-fit:cover;display:block;filter:none;transform:none}.ac-catalog-body{padding:14px;display:flex;flex-direction:column;gap:7px}.ac-catalog-body>b{min-height:40px}.ac-catalog-body>strong,.ac-modal-price{font:700 18px Georgia,serif;color:var(--rust)}.ac-fixed-note{font-size:10px;text-transform:uppercase;color:var(--rust);font-weight:800}.ac-card-actions{display:flex;gap:7px}.ac-card-actions button{flex:1;border:1px solid rgba(188,82,43,.3);background:transparent;color:var(--rust);border-radius:10px;padding:8px;font-size:11px;font-weight:800;cursor:pointer}.ac-card-actions .primary-mini{background:var(--rust);color:#fff}.ac-product-modal{display:flex;flex-direction:column;gap:8px}@media(max-width:900px){.ac-catalog-grid{grid-template-columns:repeat(2,1fr)}}@media(max-width:560px){.ac-catalog-grid{grid-template-columns:1fr}.ac-catalog-art{height:230px}}`;document.head.appendChild(s);installBrowse();const obs=new MutationObserver(()=>{if(installBrowse())obs.disconnect()});obs.observe(document.body,{childList:true,subtree:true});