// Hackathon demo guide. The walkthrough is available from the separate Demo button; no inline info buttons.
const DEMO_GUIDE=[
  {key:'hero',title:'Artisan Connect',label:'The platform',text:'A multi-art platform connecting Indian artisans, their stories, and buyers. The demo shows how AI can make traditional and contemporary art easier to discover.'},
  {key:'catalog',title:'AI Catalog',label:'For artisans',text:'Upload an artwork image and choose a buyer category. The AI turns the visual input into a structured catalog with craft, materials, technique, story, tags, confidence, and an estimated market-match percentage. Uncertain details are marked for artisan confirmation.'},
  {key:'match',title:'AI Buyer Match',label:'For buyers',text:'Tell the platform what you want, choose your budget and purpose, and select craft types such as pottery, weaving, Madhubani, Phulkari or Dhokra. AI categorizes your intent and ranks the closest artworks, with the strongest match first and similar alternatives after it.'},
  {key:'market',title:'Market Linkage',label:'The opportunity',text:'Shows the core journey: artisan creates → AI understands → artwork is cataloged → the right buyer discovers it → a new market opportunity can emerge.'},
  {key:'crafts',title:'Explore Crafts',label:'Multi-art discovery',text:'Explore different Indian art forms in one place instead of treating each craft as a separate marketplace. The goal is to help buyers discover across traditions and styles.'},
  {key:'stories',title:'Artisan Stories',label:'Human context',text:'Stories keep the artisan and cultural context visible. The technology supports discovery; it does not replace the maker’s voice.'},
  {key:'login',title:'Role-based Login',label:'Two experiences',text:'Login as a Seller/Artisan to see tools for adding work and market opportunities, or as a Buyer to discover, save and match with artworks.'},
  {key:'dashboard',title:'Dashboard',label:'Working demo',text:'The dashboard demonstrates the two sides of the platform: artisans manage their work and opportunities, while buyers discover products, artisans, saved pieces and orders.'}
];
function guideStyles(){if(document.getElementById('demo-guide-styles'))return;const s=document.createElement('style');s.id='demo-guide-styles';s.textContent=`
.demo-help-btn{position:fixed;right:18px;bottom:18px;z-index:9998;border:0;border-radius:999px;padding:12px 16px;background:#93442e;color:#fff9f0;font:700 12px 'DM Sans',sans-serif;box-shadow:0 10px 28px rgba(36,22,18,.22);cursor:pointer}.demo-help-btn:hover{background:#b85c38}
.demo-guide-backdrop{position:fixed;inset:0;z-index:10050;background:rgba(36,22,18,.68);backdrop-filter:blur(8px);display:grid;place-items:center;padding:20px}.demo-guide-modal{width:min(680px,100%);max-height:min(760px,90vh);overflow:auto;background:#fff9f0;border:1px solid rgba(74,44,34,.14);border-radius:26px;padding:30px;box-shadow:0 30px 100px rgba(36,22,18,.35);color:#241612}.demo-guide-top{display:flex;justify-content:space-between;gap:20px;align-items:flex-start}.demo-guide-modal h2{font-size:38px;margin:5px 0 8px}.demo-guide-modal p{color:#713b3b}.demo-guide-close{border:0;width:38px;height:38px;border-radius:50%;background:#f7f0e5;color:#4a2c22;font-size:22px;cursor:pointer}.demo-guide-list{display:grid;gap:10px;margin-top:20px}.demo-guide-item{display:grid;grid-template-columns:1fr auto;gap:12px;padding:15px;border:1px solid #dcc8ad;border-radius:16px;background:#f7f0e5}.demo-guide-item b{display:block;margin-bottom:4px}.demo-guide-item small{color:#b85c38;font-weight:800;text-transform:uppercase;letter-spacing:.08em}.demo-guide-item button{border:0;border-radius:10px;padding:9px 12px;background:#93442e;color:#fff9f0;font-weight:800;cursor:pointer}.demo-explain-pop{position:fixed;z-index:10051;inset:auto 18px 76px auto;width:min(360px,calc(100vw - 36px));background:#fff9f0;border:1px solid #dcc8ad;border-radius:18px;padding:18px;box-shadow:0 20px 60px rgba(36,22,18,.25)}.demo-explain-pop b{display:block;font-family:'Playfair Display',serif;font-size:22px;margin-bottom:5px}.demo-explain-pop small{color:#b85c38;font-weight:800}.demo-explain-pop p{font-size:13px;margin:8px 0 0}.demo-explain-pop button{margin-top:12px;border:0;background:transparent;color:#93442e;font-weight:800;cursor:pointer}@media(max-width:600px){.demo-help-btn{right:12px;bottom:12px}.demo-guide-modal{padding:22px}.demo-guide-modal h2{font-size:31px}}`;document.head.appendChild(s)}
function explain(item){document.querySelector('.demo-explain-pop')?.remove();const p=document.createElement('aside');p.className='demo-explain-pop';p.innerHTML=`<small>${item.label}</small><b>${item.title}</b><p>${item.text}</p><button type="button">Close</button>`;document.body.appendChild(p);p.querySelector('button').onclick=()=>p.remove()}
function openGuide(){document.querySelector('.demo-guide-backdrop')?.remove();const b=document.createElement('div');b.className='demo-guide-backdrop';b.innerHTML=`<div class="demo-guide-modal" role="dialog" aria-modal="true" aria-label="Hackathon demo guide"><div class="demo-guide-top"><div><span class="eyebrow">✦ HACKATHON DEMO</span><h2>What does everything do?</h2><p>Click any feature to get a quick explanation you can use while presenting the project.</p></div><button class="demo-guide-close" aria-label="Close">×</button></div><div class="demo-guide-list">${DEMO_GUIDE.map(x=>`<div class="demo-guide-item"><div><small>${x.label}</small><b>${x.title}</b></div><button data-demo-key="${x.key}">Explain</button></div>`).join('')}</div></div>`;document.body.appendChild(b);b.querySelector('.demo-guide-close').onclick=()=>b.remove();b.addEventListener('click',e=>{if(e.target===b)b.remove()});b.querySelectorAll('[data-demo-key]').forEach(btn=>btn.onclick=()=>explain(DEMO_GUIDE.find(x=>x.key===btn.dataset.demoKey)))}
function install(){if(window.__artisanDemoGuide)return;window.__artisanDemoGuide=true;guideStyles();const add=()=>{if(!document.querySelector('.demo-help-btn')){const b=document.createElement('button');b.className='demo-help-btn';b.type='button';b.textContent='✦ Demo guide';b.onclick=openGuide;document.body.appendChild(b)}};new MutationObserver(()=>requestAnimationFrame(add)).observe(document.body,{subtree:true,childList:true});add();setTimeout(add,500)}
install();
