import React,{useState}from'react';
import{createRoot}from'react-dom/client';
import'./styles.css';

const crafts=['Madhubani','Warli','Pattachitra','Kalamkari','Phulkari','Dhokra','Pottery','Weaving','Woodcraft','Contemporary Art'];
const products=[['Hand-painted Madhubani Panel','Madhubani','₹4,800'],['Dhokra Lotus Vessel','Dhokra','₹3,200'],['Kalamkari Textile Study','Kalamkari','₹6,400'],['Handwoven Earth Rug','Weaving','₹8,900'],['Warli Story Panel','Warli','₹5,200'],['Pattachitra Bird Artwork','Pattachitra','₹4,600']];
const buyerInterests=['Madhubani','Dhokra','Kalamkari','Weaving','Warli','Pattachitra','Pottery','Jewellery','Home Decor','Textile Art','Sculpture','Woodcraft'];
const budgets=['Under ₹1,000','₹1,000 – ₹2,500','₹2,500 – ₹5,000','₹5,000 – ₹10,000','₹10,000 – ₹25,000','₹25,000 – ₹50,000','₹50,000 – ₹1,00,000','₹1,00,000+','No fixed budget'];
const langs=<><option value="en">English</option><option value="hi">हिन्दी</option><option value="bn">বাংলা</option><option value="mr">मराठी</option><option value="gu">ગુજરાતી</option><option value="ta">தமிழ்</option><option value="te">తెలుగు</option><option value="kn">ಕನ್ನಡ</option><option value="ml">മലയാളം</option><option value="or">ଓଡ଼ିଆ</option><option value="pa">ਪੰਜਾਬੀ</option><option value="as">অসমীয়া</option></>;
const copy={en:{nav:['Explore Crafts','AI Tools','Stories','About'],hero:'Where heritage finds its next chapter.',sub:"Artisan Connect brings India's diverse artistic traditions into the modern marketplace — helping artisans tell their stories, reach new buyers, and discover new opportunities with AI.",artisan:"I'm an artisan →",buyer:"I'm a buyer →",explore:'Many traditions. One connected platform.',market:'From local craft to new markets.',stories:'Every craft carries a story.',final:'Your craft deserves a bigger stage.'},hi:{nav:['शिल्प देखें','AI टूल्स','कहानियाँ','हमारे बारे में'],hero:'जहाँ विरासत अपना अगला अध्याय लिखती है।',sub:'Artisan Connect भारत की विविध कलात्मक परंपराओं को आधुनिक बाज़ार से जोड़ता है।',artisan:'मैं एक कारीगर हूँ →',buyer:'मैं एक खरीदार हूँ →',explore:'अनेक परंपराएँ। एक जुड़ा हुआ मंच।',market:'स्थानीय शिल्प से नए बाज़ारों तक।',stories:'हर शिल्प की एक कहानी है।',final:'आपके शिल्प को एक बड़े मंच की ज़रूरत है।'}};
const readJSON=(key,fallback)=>{try{return JSON.parse(localStorage.getItem(key)||'')||fallback}catch{return fallback}};

function App(){
  const[lang,setLang]=useState(localStorage.getItem('ac-lang')||'en');
  const[login,setLogin]=useState(false);
  const[role,setRole]=useState('buyer');
  const[loggedIn,setLoggedIn]=useState(localStorage.getItem('ac-user-role')||'');
  const t=copy[lang]||copy.en;
  const change=e=>{setLang(e.target.value);localStorage.setItem('ac-lang',e.target.value);setTimeout(()=>location.reload(),20)};
  const finishLogin=e=>{e.preventDefault();localStorage.setItem('ac-user-role',role);setLoggedIn(role);setLogin(false)};
  const logout=()=>{localStorage.removeItem('ac-user-role');location.replace(location.pathname)};
  if(loggedIn)return <Dashboard role={loggedIn} lang={lang} change={change} logout={logout}/>;
  return <><header><a className="logo" href="#">✦ Artisan Connect</a><nav>{t.nav.map((x,i)=><a href={['#crafts','#ai','#stories','#about'][i]} key={x}>{x}</a>)}</nav><div className="head-actions"><select value={lang} onChange={change} aria-label="Language">{langs}</select><button className="login" onClick={()=>{setRole('buyer');setLogin(true)}}>Login <span>→</span></button></div></header><main>
    <section className="hero"><div><span className="eyebrow">INDIAN HERITAGE × HUMAN STORIES × AI</span><h1>{t.hero}</h1><p>{t.sub}</p><div className="actions"><button className="btn primary" onClick={()=>{setRole('artisan');setLogin(true)}}>{t.artisan}</button><button className="btn secondary" onClick={()=>{setRole('buyer');setLogin(true)}}>{t.buyer}</button></div><a className="text-link" href="#ai">See how AI helps →</a></div><div className="hero-art"><div className="arch"><div className="motif">✦</div><strong>HANDMADE<br/>WITH MEMORY</strong><small>India · Craft · Story</small></div><div className="insight">✦ AI insight<br/><b>Personalized Match</b></div></div></section>
    <section id="crafts"><span className="eyebrow">EXPLORE</span><h2>{t.explore}</h2><p className="lead">From village traditions to contemporary studios, one place for India's many creative languages.</p><div className="craft-grid">{crafts.map((c,i)=><article className="craft" key={c}><div className={'craft-img i'+i}><span>{['✺','◌','✦','⌁','❋'][i%5]}</span></div><div><b>{c}</b><small>{['Bihar','Maharashtra','Odisha','Andhra Pradesh','Punjab','Chhattisgarh','Across India','Across India','Rajasthan','India'][i]}</small></div></article>)}</div></section>
    <section id="ai" className="ai-section"><div><span className="eyebrow">✦ AI CATALOG</span><h2>Turn one photograph into a market-ready story.</h2><p>Artisans can add product photos and details inside their studio. AI then helps match their work with relevant buyers.</p></div><div className="upload"><div className="result"><b>Photo → product story → buyer match</b><p>Simple, transparent and artisan-controlled.</p></div></div></section>
    <section id="market"><span className="eyebrow">MARKET LINKAGE</span><h2>{t.market}</h2><div className="journey"><div>ARTISAN</div><i>→</i><div>AI UNDERSTANDS<br/>THE PRODUCT</div><i>→</i><div className="active">PERSONALIZED MATCH</div><i>→</i><div>BUYER</div><i>→</i><div>NEW OPPORTUNITY</div></div></section>
    <section id="stories"><span className="eyebrow">STORIES</span><h2>{t.stories}</h2><div className="stories"><article><div className="portrait">✺</div><b>Meera Devi</b><small>Madhubani · Bihar</small><p>“My paintings carry stories my grandmother taught me.”</p></article><article><div className="portrait p2">◌</div><b>Raghav Sahu</b><small>Dhokra · Chhattisgarh</small><p>“The metal remembers every hand that shapes it.”</p></article><article><div className="portrait p3">✦</div><b>Ananya Rao</b><small>Weaving · Telangana</small><p>“Tradition becomes stronger when it can travel.”</p></article></div></section>
    <section className="final"><span className="eyebrow">ARTISAN CONNECT</span><h2>{t.final}</h2><p>Join a platform built to connect India's artistic traditions with the people and markets looking for them.</p><div className="actions"><button className="btn light" onClick={()=>{setRole('artisan');setLogin(true)}}>Join as an artisan →</button><button className="btn outline" onClick={()=>{setRole('buyer');setLogin(true)}}>Continue as a buyer →</button></div></section>
  </main><footer id="about"><a className="logo">✦ Artisan Connect</a><p>Connecting India's creative heritage with its next chapter.</p><div className="footer-links">{t.nav.map(x=><a key={x}>{x}</a>)}</div></footer>{login&&<LoginModal role={role} setRole={setRole} close={()=>setLogin(false)} submit={finishLogin}/>}</>;
}

function LoginModal({role,setRole,close,submit}){return <div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&close()}><div className="login-modal"><button className="modal-close" onClick={close}>×</button><div className="role-switch"><button className={role==='artisan'?'selected':''} onClick={()=>setRole('artisan')}>Artist / Artisan</button><button className={role==='buyer'?'selected':''} onClick={()=>setRole('buyer')}>Buyer / Collector</button></div><span className="eyebrow">{role==='artisan'?'ARTISAN ACCESS':'BUYER ACCESS'}</span><h2>{role==='artisan'?'Your craft deserves a bigger stage.':'Discover objects with a story.'}</h2><form onSubmit={submit}><label>Email<input type="email" placeholder="you@example.com" required/></label><label>Password<input type="password" placeholder="Enter your password" required/></label><button className="modal-submit" type="submit">{role==='artisan'?'Login as an artisan':'Login as a buyer'} →</button></form></div></div>}

function Dashboard({role,lang,change,logout}){
  const artisan=role==='artisan';
  const emptyProfile={name:'',craft:'',location:'',phone:'',price:'',materials:'',bio:'',story:''};
  const[profile,setProfile]=useState(()=>({...emptyProfile,...readJSON('ac-artisan-profile',{})}));
  const[artworks,setArtworks]=useState([]);
  const[image,setImage]=useState(null);
  const[screen,setScreen]=useState(artisan?(profile.name?'seller-home':'profile'):'setup');
  const[buyer,setBuyer]=useState(()=>({name:'',phone:'',address:'',budget:'',interests:[],...readJSON('ac-buyer-details',{})}));
  const[recommendations,setRecommendations]=useState([]);
  const[loading,setLoading]=useState(false);
  const[checkout,setCheckout]=useState(null);
  const[orders,setOrders]=useState(()=>readJSON('ac-demo-orders',[]));
  const[notice,setNotice]=useState('');
  const saveProfile=e=>{e.preventDefault();localStorage.setItem('ac-artisan-profile',JSON.stringify(profile));setNotice('Your seller profile is saved.');setScreen('seller-home')};
  const addArtwork=e=>{e.preventDefault();if(!image){setNotice('Please add an artwork photo first.');return}const f=new FormData(e.currentTarget);setArtworks(a=>[...a,{title:f.get('title'),price:f.get('price'),craft:f.get('craft'),materials:f.get('materials'),image:URL.createObjectURL(image)}]);setImage(null);e.currentTarget.reset();setNotice('Artwork added to your seller showcase.');setScreen('seller-home')};
  const getRecommendations=async()=>{if(!buyer.name||!buyer.phone||!buyer.address||!buyer.budget||!buyer.interests.length){setNotice('Please complete all buyer details and select at least one interest.');return}localStorage.setItem('ac-buyer-details',JSON.stringify(buyer));setLoading(true);try{const r=await fetch('/api/buyer-match',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({selectedCrafts:buyer.interests,preferences:buyer.interests.join(', '),purpose:`Budget: ${buyer.budget}`,buyerDetails:buyer})});const raw=await r.text();const d=raw?JSON.parse(raw):{};if(!r.ok)throw Error();setRecommendations((d.matches||[]).map(m=>({...m,product:m.product||{}})));}catch{setRecommendations(products.map((p,i)=>({match_percentage:94-i*5,match_level:'Recommended',reason:`Matches your interest in ${p[1]} and your selected budget.`,product:{title:p[0],craft:p[1],price:p[2],location:'India'}})));}finally{setLoading(false);setScreen('shop')}};
  const placeOrder=(product,payment)=>{const order={id:Date.now(),title:product.title,craft:product.craft,price:product.price,payment,buyer,status:'New'};const next=[...orders,order];setOrders(next);localStorage.setItem('ac-demo-orders',JSON.stringify(next));setCheckout({success:true})};
  const sellerNav=[['seller-home','Overview'],['profile','Seller profile'],['add','Add artwork'],['opportunities','Market opportunities']];
  const buyerNav=[['setup','Buyer details'],['shop','AI suggestions'],['saved','Saved pieces'],['artists','Artisans'],['orders','My orders']];
  return <div className="dashboard"><header className="dashboard-header"><a className="logo" href="#">✦ Artisan Connect</a><div className="dashboard-user"><select value={lang} onChange={change} aria-label="Language">{langs}</select><span className="role-chip">{artisan?'Artist / Artisan':'Buyer / Collector'}</span><button className="logout" onClick={logout}>Log out</button></div></header><main className="dashboard-main"><aside className="dashboard-sidebar"><span className="eyebrow">{artisan?'SELLER SPACE':'BUYER SPACE'}</span><h2>{artisan?'Your studio':'Your collection'}</h2>{(artisan?sellerNav:buyerNav).map(x=><button key={x[0]} className={screen===x[0]?'active':''} onClick={()=>setScreen(x[0])}>{x[1]} <span>→</span></button>)}<button className="sidebar-logout" onClick={logout}>Log out</button></aside><div className="dashboard-content">{artisan?<>{screen==='profile'&&<SellerProfile profile={profile} setProfile={setProfile} save={saveProfile}/>} {screen==='add'&&<AddArtwork image={image} setImage={setImage} addArtwork={addArtwork}/>} {screen==='opportunities'&&<SellerOpportunities profile={profile}/>} {screen==='seller-home'&&<SellerHome profile={profile} artworks={artworks} orders={orders} setScreen={setScreen}/>}</>:<>{screen==='setup'&&<BuyerSetup buyer={buyer} setBuyer={setBuyer} next={getRecommendations} loading={loading}/>} {screen==='shop'&&<BuyerShop recommendations={recommendations.length?recommendations:products.map((p,i)=>({match_percentage:90-i*4,product:{title:p[0],craft:p[1],price:p[2],location:'India'},reason:'Suggested from the current catalog.'}))} buy={setCheckout}/>} {screen==='saved'&&<BuyerSaved/>} {screen==='artists'&&<BuyerArtists/>} {screen==='orders'&&<BuyerOrders orders={orders}/>}</>}{notice&&<div className="dashboard-notice">{notice}<button onClick={()=>setNotice('')}>×</button></div>}</div></main>{checkout&&<Checkout product={checkout} buyer={buyer} close={()=>setCheckout(null)} place={placeOrder}/>}</div>;
}

function BuyerSetup({buyer,setBuyer,next,loading}){const toggle=x=>setBuyer({...buyer,interests:buyer.interests.includes(x)?buyer.interests.filter(i=>i!==x):[...buyer.interests,x]});return <section className="workspace-panel"><span className="eyebrow">✦ PERSONALIZED DISCOVERY</span><h1>Tell us a little about you.</h1><p className="workspace-intro">Enter your details, choose a budget and select the products you like. AI suggestions come next.</p><div className="seller-form"><div className="form-grid"><label>Your name<input value={buyer.name} onChange={e=>setBuyer({...buyer,name:e.target.value})}/></label><label>Contact phone<input type="tel" value={buyer.phone} onChange={e=>setBuyer({...buyer,phone:e.target.value})}/></label><label>Delivery address<textarea rows="3" value={buyer.address} onChange={e=>setBuyer({...buyer,address:e.target.value})}/></label><label>Budget range<select value={buyer.budget} onChange={e=>setBuyer({...buyer,budget:e.target.value})}><option value="">Choose your budget</option>{budgets.map(x=><option key={x}>{x}</option>)}</select></label></div><label>What are you interested in?</label><div className="buyer-craft-options">{buyerInterests.map(x=><button type="button" key={x} className={buyer.interests.includes(x)?'selected':''} onClick={()=>toggle(x)}>{x}</button>)}</div><button className="btn primary" onClick={next} disabled={loading}>{loading?'Creating AI suggestions…':'Next — Get AI suggestions →'}</button></div></section>}

function BuyerShop({recommendations,buy}){return <section className="workspace-panel"><span className="eyebrow">✦ AI MATCH</span><h1>AI suggested for you.</h1><p className="workspace-intro">Recommendations based on your buyer details, budget and selected interests.</p><div className="buyer-products">{recommendations.map((m,i)=>{const p=m.product||{};return <article key={(p.title||'art')+i}><div className={'product i'+(i%4)}></div><div className="buyer-product-info"><small>{p.craft||'Artwork'} · {p.location||'India'}</small><b>{p.title||'Artwork'}</b><strong>{p.price||'Price on request'}</strong><small>{m.match_percentage||90}% match</small><p>{m.reason||''}</p><button className="btn primary" onClick={()=>buy(p)}>Buy now →</button></div></article>})}</div></section>}

function Checkout({product,buyer,close,place}){const[payment,setPayment]=useState('UPI');const[done,setDone]=useState(false);if(done)return <div className="modal-backdrop"><div className="login-modal"><button className="modal-close" onClick={close}>×</button><span className="eyebrow">ORDER CONFIRMED</span><h2>Order placed successfully!</h2><p>This is a hackathon demo checkout. No real payment was charged.</p><button className="btn primary" onClick={close}>Continue shopping</button></div></div>;return <div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&close()}><div className="login-modal"><button className="modal-close" onClick={close}>×</button><span className="eyebrow">CHECKOUT</span><h2>{product.title||'Artwork'}</h2><p><b>{product.price||'Price on request'}</b></p><p><b>Deliver to</b><br/>{buyer.name}<br/>{buyer.phone}<br/>{buyer.address}</p><label>Choose payment method<select value={payment} onChange={e=>setPayment(e.target.value)}><option>UPI</option><option>Card</option><option>Cash on Delivery</option></select></label>{payment==='UPI'&&<label>UPI ID<input placeholder="name@upi"/></label>}{payment==='Card'&&<label>Card number<input placeholder="1234 5678 9012 3456"/></label>}<button className="modal-submit" onClick={()=>{place(product,payment);setDone(true)}}>Place demo order →</button></div></div>}

function SellerProfile({profile,setProfile,save}){const field=(key,label,placeholder,type='text')=><label>{label}<input type={type} value={profile[key]} onChange={e=>setProfile({...profile,[key]:e.target.value})} placeholder={placeholder} required={['name','craft','location','phone'].includes(key)}/></label>;return <section className="workspace-panel"><span className="eyebrow">SELLER PROFILE</span><h1>Tell buyers about your craft.</h1><p className="workspace-intro">Create the profile buyers will see. Keep cultural, material and origin details in your own words.</p><form className="seller-form" onSubmit={save}><div className="form-grid">{field('name','Artist / artisan name','Your name')}{field('phone','Contact phone','Phone number','tel')}{field('craft','Primary art form','Madhubani, weaving, pottery…')}{field('location','Location','Village / city, state')}{field('price','Typical price range','₹2,000 – ₹8,000')}{field('materials','Materials','Cotton, clay, metal…')}</div><label>About your work<textarea value={profile.bio} onChange={e=>setProfile({...profile,bio:e.target.value})} rows="4"/></label><label>Your story<textarea value={profile.story} onChange={e=>setProfile({...profile,story:e.target.value})} rows="4"/></label><button className="btn primary">Save seller profile →</button></form></section>}

function AddArtwork({image,setImage,addArtwork}){return <section className="workspace-panel"><span className="eyebrow">ADD ARTWORK</span><h1>Put your work in the marketplace.</h1><form className="seller-form" onSubmit={addArtwork}><label className="artwork-upload"><input type="file" accept="image/*" onChange={e=>setImage(e.target.files[0])}/>{image?<strong>{image.name}</strong>:<strong>＋ Add artwork photo</strong>}</label><div className="form-grid"><label>Artwork title<input name="title" required/></label><label>Price<input name="price" placeholder="₹4,500" required/></label><label>Craft / art form<input name="craft"/></label><label>Materials<input name="materials"/></label></div><label>Description<textarea name="description" rows="5"/></label><button className="btn primary">Publish artwork →</button></form></section>}

function SellerHome({profile,artworks,orders,setScreen}){const earnings=orders.reduce((s,o)=>s+Number(String(o.price||'').replace(/[^0-9]/g,'')),0);return <section className="workspace-panel"><div className="workspace-heading"><div><span className="eyebrow">SELLER OVERVIEW</span><h1>{profile.name||'Your creator studio'}</h1><p>{profile.craft?`${profile.craft} · ${profile.location}`:'Complete your profile to start showcasing your work.'}</p></div><button className="btn primary" onClick={()=>setScreen('add')}>＋ Add artwork</button></div><div className="seller-stats"><div><strong>{artworks.length}</strong><span>Published works</span></div><div><strong>{orders.length}</strong><span>Buyer orders</span></div><div><strong>₹{earnings.toLocaleString('en-IN')}</strong><span>Demo earnings</span></div></div><div className="seller-empty">{orders.length?<div className="opportunity-list">{orders.slice().reverse().map(o=><article key={o.id}><div><b>{o.title}</b><small>{o.buyer?.name} · {o.payment}</small></div><strong>{o.price}</strong><button>{o.status}</button></article>)}</div>:<><span className="empty-icon">✦</span><h2>No buyer orders yet.</h2><p>Orders placed through the demo checkout will appear here.</p></>}</div></section>}

function SellerOpportunities({profile}){return <section className="workspace-panel"><span className="eyebrow">AI MARKET LINKAGE</span><h1>Find new opportunities.</h1><p className="workspace-intro">Suggestions use your profile context: {profile.craft||'your craft'} · {profile.location||'your location'}.</p><div className="opportunity-list">{[['Boutique craft stores','Handmade home objects','92% fit'],['Museum shop collections','Story-led Indian craft','86% fit'],['Independent design buyers','Contemporary craft','81% fit']].map(x=><article key={x[0]}><div><b>{x[0]}</b><small>{x[1]}</small></div><strong>{x[2]}</strong><button>Review →</button></article>)}</div></section>}

function BuyerSaved(){return <section className="workspace-panel"><span className="eyebrow">SAVED PIECES</span><h1>Your collection starts here.</h1><div className="empty-large">♡<h2>No saved pieces yet</h2></div></section>}
function BuyerArtists(){return <section className="workspace-panel"><span className="eyebrow">ARTISANS</span><h1>Meet the makers.</h1><div className="artist-list">{[['Meera Devi','Madhubani · Bihar'],['Raghav Sahu','Dhokra · Chhattisgarh'],['Ananya Rao','Weaving · Telangana']].map(x=><article key={x[0]}><div className="portrait">✦</div><div><b>{x[0]}</b><small>{x[1]}</small></div></article>)}</div></section>}
function BuyerOrders({orders}){return <section className="workspace-panel"><span className="eyebrow">ORDERS</span><h1>Your orders.</h1>{orders.length?<div className="opportunity-list">{orders.slice().reverse().map(o=><article key={o.id}><div><b>{o.title}</b><small>{o.payment}</small></div><strong>{o.price}</strong><button>{o.status}</button></article>)}</div>:<div className="empty-large">◌<h2>No orders yet</h2></div>}</section>}

createRoot(document.getElementById('root')).render(<App/>);
