import React,{useState}from'react';
import{createRoot}from'react-dom/client';
import'./styles.css';

const crafts=['Madhubani','Warli','Pattachitra','Kalamkari','Phulkari','Dhokra','Pottery','Weaving','Woodcraft','Contemporary Art'];
const products=[['Hand-painted Madhubani Panel','Madhubani','₹4,800'],['Dhokra Lotus Vessel','Dhokra','₹3,200'],['Kalamkari Textile Study','Kalamkari','₹6,400'],['Handwoven Earth Rug','Weaving','₹8,900'],['Warli Story Panel','Warli','₹5,200'],['Pattachitra Bird Artwork','Pattachitra','₹4,600']];
const buyerInterests=['Madhubani','Dhokra','Kalamkari','Weaving','Warli','Pattachitra','Pottery','Jewellery','Home Decor','Textile Art','Sculpture','Woodcraft'];
const budgets=['Under ₹1,000','₹1,000 – ₹2,500','₹2,500 – ₹5,000','₹5,000 – ₹10,000','₹10,000 – ₹25,000','₹25,000 – ₹50,000','₹50,000 – ₹1,00,000','₹1,00,000+','No fixed budget'];
const langs=<><option value="en">English</option><option value="hi">हिन्दी</option><option value="bn">বাংলা</option><option value="mr">मराठी</option><option value="gu">ગુજરાતી</option><option value="ta">தமிழ்</option><option value="te">తెలుగు</option><option value="kn">ಕನ್ನಡ</option><option value="ml">മലയാളം</option><option value="or">ଓଡ଼ିଆ</option><option value="pa">ਪੰਜਾਬੀ</option><option value="as">অসমীয়া</option></>;
const copy={en:{nav:['Explore Crafts','AI Tools','Stories','About'],hero:'Where heritage finds its next chapter.',sub:"Artisan Connect brings India's diverse artistic traditions into the modern marketplace — helping artisans tell their stories, reach new buyers, and discover new opportunities with AI.",artisan:"I'm an artisan →",buyer:"I'm a buyer →",explore:'Many traditions. One connected platform.',market:'From local craft to new markets.',stories:'Every craft carries a story.',final:'Your craft deserves a bigger stage.'},hi:{nav:['शिल्प देखें','AI टूल्स','कहानियाँ','हमारे बारे में'],hero:'जहाँ विरासत अपना अगला अध्याय लिखती है।',sub:'Artisan Connect भारत की विविध कलात्मक परंपराओं को आधुनिक बाज़ार से जोड़ता है।',artisan:'मैं एक कारीगर हूँ →',buyer:'मैं एक खरीदार हूँ →',explore:'अनेक परंपराएँ। एक जुड़ा हुआ मंच।',market:'स्थानीय शिल्प से नए बाज़ारों तक।',stories:'हर शिल्प की एक कहानी है।',final:'आपके शिल्प को एक बड़े मंच की ज़रूरत है।'}};
const aiFlowCopy={
 en:{ey:'✦ AI CATALOG',title:'Turn one photograph into a market-ready story.',desc:'One product photo becomes a clear listing, a translated story and a smarter buyer match.',available:'Works in your selected language',steps:[['📷','Upload photo','Add one clear photo of your product from your studio.'],['✦','AI understands the craft','AI identifies visible craft, material, style and product details.'],['📝','Creates the product story','It turns those details into a clear, market-ready product story.'],['文','Translates the story','The same story is shown in your selected Indian language.'],['◎','Finds the right buyer','Your product is matched with buyers looking for similar work.']]},
 hi:{ey:'✦ AI कैटलॉग',title:'एक तस्वीर को बाज़ार के लिए तैयार कहानी में बदलें।',desc:'एक उत्पाद फोटो से स्पष्ट लिस्टिंग, अनुवादित कहानी और सही खरीदार का मिलान तैयार होता है।',available:'आपकी चुनी हुई भाषा में उपलब्ध',steps:[['📷','फोटो अपलोड करें','अपने उत्पाद की एक साफ़ तस्वीर स्टूडियो से जोड़ें।'],['✦','AI शिल्प को समझता है','AI दिखाई देने वाले शिल्प, सामग्री, शैली और उत्पाद विवरण पहचानता है।'],['📝','उत्पाद की कहानी बनती है','इन विवरणों से एक स्पष्ट, बाज़ार के लिए तैयार कहानी बनती है।'],['文','कहानी का अनुवाद','यही कहानी आपकी चुनी हुई भारतीय भाषा में दिखाई जाती है।'],['◎','सही खरीदार खोजे','उत्पाद को समान काम खोज रहे खरीदारों से मिलाया जाता है।']]},
 bn:{ey:'✦ AI ক্যাটালগ',title:'একটি ছবিকে বাজারের জন্য প্রস্তুত গল্পে বদলান।',desc:'একটি পণ্যের ছবি থেকে পরিষ্কার তালিকা, অনূদিত গল্প এবং সঠিক ক্রেতার মিল তৈরি হয়।',available:'আপনার নির্বাচিত ভাষায় উপলভ্য',steps:[['📷','ছবি আপলোড করুন','স্টুডিও থেকে আপনার পণ্যের একটি পরিষ্কার ছবি যোগ করুন।'],['✦','AI কারুশিল্প বোঝে','AI দৃশ্যমান কারুশিল্প, উপাদান, শৈলী ও পণ্যের তথ্য শনাক্ত করে।'],['📝','পণ্যের গল্প তৈরি','তথ্যগুলোকে বাজারের জন্য প্রস্তুত একটি স্পষ্ট গল্পে রূপ দেয়।'],['文','গল্প অনুবাদ করে','একই গল্প আপনার নির্বাচিত ভারতীয় ভাষায় দেখানো হয়।'],['◎','সঠিক ক্রেতা খোঁজে','পণ্যটি মিলযুক্ত কাজ খোঁজা ক্রেতাদের সঙ্গে মেলানো হয়।']]},
 mr:{ey:'✦ AI कॅटलॉग',title:'एका फोटोला बाजारासाठी तयार कथेत बदला.',desc:'एका उत्पादनाच्या फोटोमधून स्पष्ट लिस्टिंग, भाषांतरित कथा आणि योग्य खरेदीदाराशी जुळवणी तयार होते.',available:'तुमच्या निवडलेल्या भाषेत उपलब्ध',steps:[['📷','फोटो अपलोड करा','स्टुडिओमधून तुमच्या उत्पादनाचा एक स्पष्ट फोटो जोडा.'],['✦','AI हस्तकला समजते','AI दिसणारी कला, साहित्य, शैली आणि उत्पादन तपशील ओळखते.'],['📝','उत्पादनाची कथा तयार','तपशीलांपासून बाजारासाठी तयार स्पष्ट कथा बनते.'],['文','कथेचे भाषांतर','तीच कथा तुमच्या निवडलेल्या भारतीय भाषेत दिसते.'],['◎','योग्य खरेदीदार शोधते','तुमचे उत्पादन अशा कामाचा शोध घेणाऱ्या खरेदीदारांशी जुळवले जाते.']]},
 gu:{ey:'✦ AI કેટલોગ',title:'એક ફોટોને બજાર માટે તૈયાર વાર્તામાં ફેરવો.',desc:'એક ઉત્પાદન ફોટાથી સ્પષ્ટ લિસ્ટિંગ, અનુવાદિત વાર્તા અને યોગ્ય ખરીદદારનું મેચિંગ બને છે.',available:'તમારી પસંદ કરેલી ભાષામાં ઉપલબ્ધ',steps:[['📷','ફોટો અપલોડ કરો','તમારા સ્ટુડિયોમાંથી ઉત્પાદનનો એક સ્પષ્ટ ફોટો ઉમેરો.'],['✦','AI હસ્તકલા સમજે છે','AI દેખાતી કલા, સામગ્રી, શૈલી અને ઉત્પાદન વિગતો ઓળખે છે.'],['📝','ઉત્પાદનની વાર્તા બનાવે છે','આ વિગતોને બજાર માટે તૈયાર સ્પષ્ટ વાર્તામાં ફેરવે છે.'],['文','વાર્તાનો અનુવાદ','એ જ વાર્તા તમારી પસંદ કરેલી ભારતીય ભાષામાં દેખાય છે.'],['◎','યોગ્ય ખરીદદાર શોધે છે','ઉત્પાદનને સમાન કામ શોધતા ખરીદદારો સાથે મેચ કરવામાં આવે છે.']]},
 ta:{ey:'✦ AI பட்டியல்',title:'ஒரு புகைப்படத்தை சந்தைக்குத் தயாரான கதையாக மாற்றுங்கள்.',desc:'ஒரு தயாரிப்பு புகைப்படம் தெளிவான பட்டியல், மொழிபெயர்க்கப்பட்ட கதை மற்றும் சரியான வாங்குபவர் பொருத்தமாக மாறுகிறது.',available:'நீங்கள் தேர்ந்தெடுத்த மொழியில் கிடைக்கும்',steps:[['📷','புகைப்படம் பதிவேற்றவும்','உங்கள் ஸ்டுடியோவில் இருந்து தயாரிப்பின் தெளிவான புகைப்படத்தை சேர்க்கவும்.'],['✦','AI கைவினையை புரிகிறது','AI கைவினை, பொருள், பாணி மற்றும் தயாரிப்பு விவரங்களை கண்டறிகிறது.'],['📝','தயாரிப்பு கதையை உருவாக்கும்','அந்த விவரங்களை சந்தைக்குத் தயாரான தெளிவான கதையாக மாற்றுகிறது.'],['文','கதையை மொழிபெயர்க்கும்','அதே கதை நீங்கள் தேர்ந்தெடுத்த இந்திய மொழியில் காட்டப்படும்.'],['◎','சரியான வாங்குபவரை கண்டறியும்','ஒத்த பொருட்களை தேடும் வாங்குபவர்களுடன் உங்கள் தயாரிப்பு பொருத்தப்படும்.']]},
 te:{ey:'✦ AI కాటలాగ్',title:'ఒక ఫోటోను మార్కెట్‌కు సిద్ధమైన కథగా మార్చండి.',desc:'ఒక ఉత్పత్తి ఫోటో స్పష్టమైన లిస్టింగ్, అనువదించిన కథ మరియు సరైన కొనుగోలుదారుతో మ్యాచ్‌గా మారుతుంది.',available:'మీరు ఎంచుకున్న భాషలో అందుబాటులో ఉంది',steps:[['📷','ఫోటో అప్లోడ్ చేయండి','మీ స్టూడియో నుంచి ఉత్పత్తి యొక్క స్పష్టమైన ఫోటోను జోడించండి.'],['✦','AI కళను అర్థం చేసుకుంటుంది','AI కనిపించే కళ, పదార్థం, శైలి మరియు ఉత్పత్తి వివరాలను గుర్తిస్తుంది.'],['📝','ఉత్పత్తి కథను సృష్టిస్తుంది','ఆ వివరాలను మార్కెట్‌కు సిద్ధమైన స్పష్టమైన కథగా మార్చుతుంది.'],['文','కథను అనువదిస్తుంది','అదే కథ మీ ఎంపిక చేసిన భారతీయ భాషలో కనిపిస్తుంది.'],['◎','సరైన కొనుగోలుదారును కనుగొంటుంది','ఇలాంటి పనిని వెతుకుతున్న కొనుగోలుదారులతో ఉత్పత్తి మ్యాచ్ అవుతుంది.']]},
 kn:{ey:'✦ AI ಕ್ಯಾಟಲಾಗ್',title:'ಒಂದು ಫೋಟೋವನ್ನು ಮಾರುಕಟ್ಟೆಗೆ ಸಿದ್ಧವಾದ ಕಥೆಯಾಗಿ ಮಾಡಿ.',desc:'ಒಂದು ಉತ್ಪನ್ನದ ಫೋಟೋ ಸ್ಪಷ್ಟ ಲಿಸ್ಟಿಂಗ್, ಅನುವಾದಿತ ಕಥೆ ಮತ್ತು ಸರಿಯಾದ ಖರೀದಿದಾರರ ಹೊಂದಾಣಿಕೆಯಾಗುತ್ತದೆ.',available:'ನೀವು ಆಯ್ಕೆ ಮಾಡಿದ ಭಾಷೆಯಲ್ಲಿ ಲಭ್ಯ',steps:[['📷','ಫೋಟೋ ಅಪ್ಲೋಡ್ ಮಾಡಿ','ನಿಮ್ಮ ಸ್ಟುಡಿಯೋದ ಉತ್ಪನ್ನದ ಒಂದು ಸ್ಪಷ್ಟ ಫೋಟೋ ಸೇರಿಸಿ.'],['✦','AI ಕರಕುಶಲವನ್ನು ಅರ್ಥಮಾಡಿಕೊಳ್ಳುತ್ತದೆ','AI ಕಾಣುವ ಕಲೆ, ವಸ್ತು, ಶೈಲಿ ಮತ್ತು ಉತ್ಪನ್ನದ ವಿವರಗಳನ್ನು ಗುರುತಿಸುತ್ತದೆ.'],['📝','ಉತ್ಪನ್ನ ಕಥೆ ರಚಿಸುತ್ತದೆ','ವಿವರಗಳನ್ನು ಮಾರುಕಟ್ಟೆಗೆ ಸಿದ್ಧವಾದ ಸ್ಪಷ್ಟ ಕಥೆಯಾಗಿ ಮಾಡುತ್ತದೆ.'],['文','ಕಥೆಯನ್ನು ಅನುವಾದಿಸುತ್ತದೆ','ಅದೇ ಕಥೆ ನೀವು ಆಯ್ಕೆ ಮಾಡಿದ ಭಾರತೀಯ ಭಾಷೆಯಲ್ಲಿ ಕಾಣುತ್ತದೆ.'],['◎','ಸರಿಯಾದ ಖರೀದಿದಾರರನ್ನು ಹುಡುಕುತ್ತದೆ','ಇಂತಹ ಕೆಲಸ ಹುಡುಕುತ್ತಿರುವ ಖರೀದಿದಾರರೊಂದಿಗೆ ಉತ್ಪನ್ನವನ್ನು ಹೊಂದಿಸಲಾಗುತ್ತದೆ.']]},
 ml:{ey:'✦ AI കാറ്റലോഗ്',title:'ഒരു ഫോട്ടോയെ വിപണിക്ക് തയ്യാറായ കഥയാക്കി മാറ്റൂ.',desc:'ഒരു ഉൽപ്പന്ന ഫോട്ടോ വ്യക്തമായ ലിസ്റ്റിംഗ്, പരിഭാഷപ്പെടുത്തിയ കഥ, ശരിയായ വാങ്ങുന്നവരുമായി പൊരുത്തം എന്നിവയായി മാറുന്നു.',available:'നിങ്ങൾ തിരഞ്ഞെടുത്ത ഭാഷയിൽ ലഭ്യമാണ്',steps:[['📷','ഫോട്ടോ അപ്‌ലോഡ് ചെയ്യുക','നിങ്ങളുടെ സ്റ്റുഡിയോയിൽ നിന്ന് ഉൽപ്പന്നത്തിന്റെ വ്യക്തമായ ഒരു ഫോട്ടോ ചേർക്കുക.'],['✦','AI കരകൗശലം മനസ്സിലാക്കുന്നു','AI ദൃശ്യമായ കരകൗശലം, വസ്തു, ശൈലി, ഉൽപ്പന്ന വിശദാംശങ്ങൾ തിരിച്ചറിയുന്നു.'],['📝','ഉൽപ്പന്ന കഥ സൃഷ്ടിക്കുന്നു','ആ വിവരങ്ങളെ വിപണിക്ക് തയ്യാറായ വ്യക്തമായ കഥയാക്കി മാറ്റുന്നു.'],['文','കഥ പരിഭാഷപ്പെടുത്തുന്നു','അതേ കഥ നിങ്ങൾ തിരഞ്ഞെടുത്ത ഇന്ത്യൻ ഭാഷയിൽ കാണിക്കും.'],['◎','ശരിയായ വാങ്ങുന്നവരെ കണ്ടെത്തുന്നു','സമാന ഉൽപ്പന്നങ്ങൾ അന്വേഷിക്കുന്ന വാങ്ങുന്നവരുമായി ഇത് പൊരുത്തപ്പെടുത്തുന്നു.']]},
 or:{ey:'✦ AI କ୍ୟାଟାଲଗ୍',title:'ଗୋଟିଏ ଫଟୋକୁ ବଜାର ପାଇଁ ପ୍ରସ୍ତୁତ କାହାଣୀରେ ପରିବର୍ତ୍ତନ କରନ୍ତୁ।',desc:'ଗୋଟିଏ ପଣ୍ୟ ଫଟୋରୁ ସ୍ପଷ୍ଟ ଲିଷ୍ଟିଂ, ଅନୁବାଦିତ କାହାଣୀ ଏବଂ ଠିକ୍ କ୍ରେତା ମ୍ୟାଚ୍ ତିଆରି ହୁଏ।',available:'ଆପଣ ବାଛିଥିବା ଭାଷାରେ ଉପଲବ୍ଧ',steps:[['📷','ଫଟୋ ଅପଲୋଡ୍ କରନ୍ତୁ','ଆପଣଙ୍କ ଷ୍ଟୁଡିଓରୁ ପଣ୍ୟର ଗୋଟିଏ ସ୍ପଷ୍ଟ ଫଟୋ ଯୋଡନ୍ତୁ।'],['✦','AI ଶିଳ୍ପକୁ ବୁଝେ','AI ଦେଖାଯାଉଥିବା ଶିଳ୍ପ, ସାମଗ୍ରୀ, ଶୈଳୀ ଓ ପଣ୍ୟ ବିବରଣୀ ଚିହ୍ନଟ କରେ।'],['📝','ପଣ୍ୟ କାହାଣୀ ତିଆରି କରେ','ବିବରଣୀକୁ ବଜାର ପାଇଁ ପ୍ରସ୍ତୁତ ସ୍ପଷ୍ଟ କାହାଣୀରେ ପରିଣତ କରେ।'],['文','କାହାଣୀ ଅନୁବାଦ କରେ','ସେହି କାହାଣୀ ଆପଣ ବାଛିଥିବା ଭାରତୀୟ ଭାଷାରେ ଦେଖାଯାଏ।'],['◎','ଠିକ୍ କ୍ରେତା ଖୋଜେ','ସମାନ କାମ ଖୋଜୁଥିବା କ୍ରେତାଙ୍କ ସହ ପଣ୍ୟକୁ ମେଳ କରାଯାଏ।']]},
 pa:{ey:'✦ AI ਕੈਟਾਲੌਗ',title:'ਇੱਕ ਫੋਟੋ ਨੂੰ ਮਾਰਕੀਟ ਲਈ ਤਿਆਰ ਕਹਾਣੀ ਵਿੱਚ ਬਦਲੋ।',desc:'ਇੱਕ ਉਤਪਾਦ ਫੋਟੋ ਤੋਂ ਸਾਫ਼ ਲਿਸਟਿੰਗ, ਅਨੁਵਾਦਿਤ ਕਹਾਣੀ ਅਤੇ ਸਹੀ ਖਰੀਦਦਾਰ ਨਾਲ ਮੈਚ ਬਣਦਾ ਹੈ।',available:'ਤੁਹਾਡੀ ਚੁਣੀ ਹੋਈ ਭਾਸ਼ਾ ਵਿੱਚ ਉਪਲਬਧ',steps:[['📷','ਫੋਟੋ ਅਪਲੋਡ ਕਰੋ','ਆਪਣੇ ਸਟੂਡੀਓ ਤੋਂ ਉਤਪਾਦ ਦੀ ਇੱਕ ਸਾਫ਼ ਫੋਟੋ ਜੋੜੋ।'],['✦','AI ਕਲਾ ਨੂੰ ਸਮਝਦਾ ਹੈ','AI ਦਿਖਾਈ ਦੇਣ ਵਾਲੀ ਕਲਾ, ਸਮੱਗਰੀ, ਸਟਾਈਲ ਅਤੇ ਉਤਪਾਦ ਵੇਰਵੇ ਪਛਾਣਦਾ ਹੈ।'],['📝','ਉਤਪਾਦ ਦੀ ਕਹਾਣੀ ਬਣਾਉਂਦਾ ਹੈ','ਇਹ ਵੇਰਵੇ ਮਾਰਕੀਟ ਲਈ ਤਿਆਰ ਸਪਸ਼ਟ ਕਹਾਣੀ ਵਿੱਚ ਬਦਲਦਾ ਹੈ।'],['文','ਕਹਾਣੀ ਦਾ ਅਨੁਵਾਦ','ਉਹੀ ਕਹਾਣੀ ਤੁਹਾਡੀ ਚੁਣੀ ਭਾਰਤੀ ਭਾਸ਼ਾ ਵਿੱਚ ਦਿਖਾਈ ਜਾਂਦੀ ਹੈ।'],['◎','ਸਹੀ ਖਰੀਦਦਾਰ ਲੱਭਦਾ ਹੈ','ਉਤਪਾਦ ਨੂੰ ਮਿਲਦੇ ਜੁਲਦੇ ਕੰਮ ਦੀ ਖੋਜ ਕਰ ਰਹੇ ਖਰੀਦਦਾਰਾਂ ਨਾਲ ਜੋੜਿਆ ਜਾਂਦਾ ਹੈ।']]},
 as:{ey:'✦ AI কেটেলগ',title:'এখন ফটো এখনক বজাৰৰ বাবে সাজু কাহিনীলৈ ৰূপান্তৰ কৰক।',desc:'এটা পণ্যৰ ফটো স্পষ্ট তালিকা, অনুবাদিত কাহিনী আৰু উপযুক্ত ক্ৰেতাৰ মিললৈ পৰিণত হয়।',available:'আপুনি নিৰ্বাচন কৰা ভাষাত উপলব্ধ',steps:[['📷','ফটো আপলোড কৰক','আপোনাৰ ষ্টুডিঅ’ৰ পৰা পণ্যৰ এখন স্পষ্ট ফটো যোগ কৰক।'],['✦','AI শিল্পক বুজে','AI দৃশ্যমান শিল্প, সামগ্ৰী, শৈলী আৰু পণ্যৰ তথ্য চিনাক্ত কৰে।'],['📝','পণ্যৰ কাহিনী তৈয়াৰ কৰে','তথ্যসমূহক বজাৰৰ বাবে সাজু স্পষ্ট কাহিনীলৈ ৰূপান্তৰ কৰে।'],['文','কাহিনী অনুবাদ কৰে','একেটা কাহিনী আপোনাৰ নিৰ্বাচিত ভাৰতীয় ভাষাত দেখুওৱা হয়।'],['◎','সঠিক ক্ৰেতা বিচাৰে','এনে কাম বিচৰা ক্ৰেতাৰ সৈতে আপোনাৰ পণ্য মিলোৱা হয়।']]}
};
const readJSON=(key,fallback)=>{try{return JSON.parse(localStorage.getItem(key)||'')||fallback}catch{return fallback}};

function App(){
  const[lang,setLang]=useState(localStorage.getItem('ac-lang')||'en');
  const[login,setLogin]=useState(false);
  const[role,setRole]=useState('buyer');
  const[loggedIn,setLoggedIn]=useState(localStorage.getItem('ac-user-role')||'');
  const t=copy[lang]||copy.en;
  const ai=aiFlowCopy[lang]||aiFlowCopy.en;
  const change=e=>{setLang(e.target.value);localStorage.setItem('ac-lang',e.target.value);setTimeout(()=>location.reload(),20)};
  const finishLogin=e=>{e.preventDefault();localStorage.setItem('ac-user-role',role);setLoggedIn(role);setLogin(false)};
  const logout=()=>{localStorage.removeItem('ac-user-role');location.replace(location.pathname)};
  if(loggedIn)return <Dashboard role={loggedIn} lang={lang} change={change} logout={logout}/>;
  return <><header><a className="logo" href="#">✦ Artisan Connect</a><nav>{t.nav.map((x,i)=><a href={['#crafts','#ai','#stories','#about'][i]} key={x}>{x}</a>)}</nav><div className="head-actions"><select value={lang} onChange={change} aria-label="Language">{langs}</select><button className="login" onClick={()=>{setRole('buyer');setLogin(true)}}>Login <span>→</span></button></div></header><main>
    <section className="hero"><div><span className="eyebrow">INDIAN HERITAGE × HUMAN STORIES × AI</span><h1>{t.hero}</h1><p>{t.sub}</p><div className="actions"><button className="btn primary" onClick={()=>{setRole('artisan');setLogin(true)}}>{t.artisan}</button><button className="btn secondary" onClick={()=>{setRole('buyer');setLogin(true)}}>{t.buyer}</button></div><a className="text-link" href="#ai">See how AI helps →</a></div><div className="hero-art"><div className="arch"><div className="motif">✦</div><strong>HANDMADE<br/>WITH MEMORY</strong><small>India · Craft · Story</small></div><div className="insight">✦ AI insight<br/><b>Personalized Match</b></div></div></section>
    <section id="crafts"><span className="eyebrow">EXPLORE</span><h2>{t.explore}</h2><p className="lead">From village traditions to contemporary studios, one place for India's many creative languages.</p><div className="craft-grid">{crafts.map((c,i)=><article className="craft" key={c}><div className={'craft-img i'+i}><span>{['✺','◌','✦','⌁','❋'][i%5]}</span></div><div><b>{c}</b><small>{['Bihar','Maharashtra','Odisha','Andhra Pradesh','Punjab','Chhattisgarh','Across India','Across India','Rajasthan','India'][i]}</small></div></article>)}</div></section>
    <section id="ai" className="ai-section"><div><span className="eyebrow">{ai.ey}</span><h2>{ai.title}</h2><p>{ai.desc}</p><div style={{marginTop:18,display:'inline-flex',alignItems:'center',gap:8,padding:'9px 13px',border:'1px solid rgba(171,76,39,.24)',borderRadius:999,fontSize:13,fontWeight:700}}>◎ {ai.available}</div></div><div className="upload" style={{padding:18}}><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(135px,1fr))',gap:10}}>{ai.steps.map((s,i)=><div key={s[1]} style={{position:'relative',minHeight:205,padding:'18px 14px',border:'1px solid rgba(100,65,45,.14)',borderRadius:18,background:'rgba(255,250,242,.74)',display:'flex',flexDirection:'column',alignItems:'center',textAlign:'center'}}><span style={{position:'absolute',top:10,left:10,width:27,height:27,borderRadius:'50%',display:'grid',placeItems:'center',background:'var(--rust)',color:'white',fontSize:12,fontWeight:800}}>{i+1}</span><div style={{width:58,height:58,borderRadius:16,display:'grid',placeItems:'center',marginTop:18,marginBottom:12,background:'rgba(188,82,43,.10)',fontSize:28,color:'var(--rust)'}}>{s[0]}</div><b style={{fontSize:15,lineHeight:1.2,marginBottom:8}}>{s[1]}</b><small style={{lineHeight:1.45,opacity:.76}}>{s[2]}</small>{i<ai.steps.length-1&&<span aria-hidden="true" style={{position:'absolute',right:-10,top:'48%',fontSize:22,color:'var(--rust)',zIndex:2}}>→</span>}</div>)}</div><div style={{marginTop:12,padding:'10px 12px',borderRadius:12,background:'rgba(188,82,43,.07)',fontSize:12,textAlign:'center',fontWeight:700}}>English · हिन्दी · বাংলা · मराठी · ગુજરાતી · தமிழ் · తెలుగు · ಕನ್ನಡ · മലയാളം · ଓଡ଼ିଆ · ਪੰਜਾਬੀ · অসমীয়া</div></div></section>
    <section id="market"><span className="eyebrow">MARKET LINKAGE</span><h2>{t.market}</h2><div className="journey"><div>ARTISAN</div><i>→</i><div>AI UNDERSTANDS<br/>THE PRODUCT</div><i>→</i><div className="active">PERSONALIZED MATCH</div><i>→</i><div>BUYER</div><i>→</i><div>NEW OPPORTUNITY</div></div></section>
    <section id="stories"><span className="eyebrow">STORIES</span><h2>{t.stories}</h2><div className="stories"><article><div className="portrait">✺</div><b>Meera Devi</b><small>Madhubani · Bihar</small><p>“My paintings carry stories my grandmother taught me.”</p></article><article><div className="portrait p2">◌</div><b>Raghav Sahu</b><small>Dhokra · Chhattisgarh</small><p>“The metal remembers every hand that shapes it.”</p></article><article><div className="portrait p3">✦</div><b>Ananya Rao</b><small>Weaving · Telangana</small><p>“Tradition becomes stronger when it can travel.”</p></article></div></section>
    <section className="final"><span className="eyebrow">ARTISAN CONNECT</span><h2>{t.final}</h2><p>Join a platform built to connect India's artistic traditions with the people and markets looking for them.</p><div className="actions"><button className="btn light" onClick={()=>{setRole('artisan');setLogin(true)}}>Join as an artisan →</button><button className="btn outline" onClick={()=>{setRole('buyer');setLogin(true)}}>Continue as a buyer →</button></div></section>
  </main><footer id="about"><a className="logo">✦ Artisan Connect</a><p>Connecting India's creative heritage with its next chapter.</p><div className="footer-links">{t.nav.map(x=><a key={x}>{x}</a>)}</div></footer>{login&&<LoginModal role={role} setRole={setRole} close={()=>setLogin(false)} submit={finishLogin}/>}</>;
}

function LoginModal({role,setRole,close,submit}){return <div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&close()}><div className="login-modal"><button className="modal-close" onClick={close}>×</button><div className="role-switch"><button className={role==='artisan'?'selected':''} onClick={()=>setRole('artisan')}>Artist / Artisan</button><button className={role==='buyer'?'selected':''} onClick={()=>setRole('buyer')}>Buyer / Collector</button></div><span className="eyebrow">{role==='artisan'?'ARTISAN ACCESS':'BUYER ACCESS'}</span><h2>{role==='artisan'?'Your craft deserves a bigger stage.':'Discover objects with a story.'}</h2><form onSubmit={submit}><label>Email<input type="email" placeholder="you@example.com" required/></label><label>Password<input type="password" placeholder="Enter your password" required/></label><button className="modal-submit" type="submit">{role==='artisan'?'Login as an artisan':'Login as a buyer'} →</button></form></div></div>}

function Dashboard({role,lang,change,logout}){
  const artisan=role==='artisan';
  const emptyProfile={name:'',craft:'',location:'',phone:'',price:'',materials:'',bio:'',story:''};
  const[profile,setProfile]=useState(()=>({...emptyProfile,...readJSON('ac-artisan-profile',{})}));
  const[artworks,setArtworks]=useState([]);
  const[image,setImage]=useState(null);
  const[screen,setScreen]=useState(artisan?(profile.name?'seller-home':'profile'):'setup');
  const storedBuyer=readJSON('ac-buyer-details',{});
  const[buyer,setBuyer]=useState(()=>({name:'',phone:'',address:'',budget:'',preference:storedBuyer.preference||storedBuyer.interests?.[0]||'',...storedBuyer,preference:storedBuyer.preference||storedBuyer.interests?.[0]||''}));
  const[recommendations,setRecommendations]=useState([]);
  const[loading,setLoading]=useState(false);
  const[checkout,setCheckout]=useState(null);
  const[orders,setOrders]=useState(()=>readJSON('ac-demo-orders',[]));
  const[notice,setNotice]=useState('');
  const saveProfile=e=>{e.preventDefault();localStorage.setItem('ac-artisan-profile',JSON.stringify(profile));setNotice('Your seller profile is saved.');setScreen('seller-home')};
  const addArtwork=e=>{e.preventDefault();if(!image){setNotice('Please add an artwork photo first.');return}const f=new FormData(e.currentTarget);setArtworks(a=>[...a,{title:f.get('title'),price:f.get('price'),craft:f.get('craft'),materials:f.get('materials'),image:URL.createObjectURL(image)}]);setImage(null);e.currentTarget.reset();setNotice('Artwork added to your seller showcase.');setScreen('seller-home')};
  const getRecommendations=async()=>{if(!buyer.name||!/^[0-9]{10}$/.test(buyer.phone)||!buyer.address||!buyer.budget||!buyer.preference.trim()){setNotice('Please enter all buyer details, a valid 10-digit phone number, and choose or type one art preference.');return}localStorage.setItem('ac-buyer-details',JSON.stringify(buyer));setLoading(true);try{const r=await fetch('/api/buyer-match',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({selectedCrafts:[buyer.preference],preferences:buyer.preference,purpose:`Budget: ${buyer.budget}`,buyerDetails:buyer})});const raw=await r.text();const d=raw?JSON.parse(raw):{};if(!r.ok)throw Error();setRecommendations((d.matches||[]).map(m=>({...m,product:m.product||{}})));}catch{setRecommendations(products.map((p,i)=>({match_percentage:94-i*5,match_level:'Recommended',reason:`Matches your interest in ${buyer.preference} and your selected budget.`,product:{title:p[0],craft:p[1],price:p[2],location:'India'}})));}finally{setLoading(false);setScreen('shop')}};
  const placeOrder=(product,payment)=>{const order={id:Date.now(),title:product.title,craft:product.craft,price:product.price,payment,buyer,status:'New'};const next=[...orders,order];setOrders(next);localStorage.setItem('ac-demo-orders',JSON.stringify(next));setCheckout({success:true})};
  const sellerNav=[['seller-home','Overview'],['profile','Seller profile'],['add','Add artwork'],['opportunities','Market opportunities']];
  const buyerNav=[['setup','Buyer details'],['shop','AI suggestions'],['saved','Saved pieces'],['artists','Artisans'],['orders','My orders']];
  return <div className="dashboard"><header className="dashboard-header"><a className="logo" href="#">✦ Artisan Connect</a><div className="dashboard-user"><select value={lang} onChange={change} aria-label="Language">{langs}</select><span className="role-chip">{artisan?'Artist / Artisan':'Buyer / Collector'}</span><button className="logout" onClick={logout}>Log out</button></div></header><main className="dashboard-main"><aside className="dashboard-sidebar"><span className="eyebrow">{artisan?'SELLER SPACE':'BUYER SPACE'}</span><h2>{artisan?'Your studio':'Your collection'}</h2>{(artisan?sellerNav:buyerNav).map(x=><button key={x[0]} className={screen===x[0]?'active':''} onClick={()=>setScreen(x[0])}>{x[1]} <span>→</span></button>)}<button className="sidebar-logout" onClick={logout}>Log out</button></aside><div className="dashboard-content">{artisan?<>{screen==='profile'&&<SellerProfile profile={profile} setProfile={setProfile} save={saveProfile}/>} {screen==='add'&&<AddArtwork image={image} setImage={setImage} addArtwork={addArtwork}/>} {screen==='opportunities'&&<SellerOpportunities profile={profile}/>} {screen==='seller-home'&&<SellerHome profile={profile} artworks={artworks} orders={orders} setScreen={setScreen}/>}</>:<>{screen==='setup'&&<BuyerSetup buyer={buyer} setBuyer={setBuyer} next={getRecommendations} loading={loading}/>} {screen==='shop'&&<BuyerShop recommendations={recommendations.length?recommendations:products.map((p,i)=>({match_percentage:90-i*4,product:{title:p[0],craft:p[1],price:p[2],location:'India'},reason:'Suggested from the current catalog.'}))} buy={setCheckout}/>} {screen==='saved'&&<BuyerSaved/>} {screen==='artists'&&<BuyerArtists/>} {screen==='orders'&&<BuyerOrders orders={orders}/>}</>}{notice&&<div className="dashboard-notice">{notice}<button onClick={()=>setNotice('')}>×</button></div>}</div></main>{checkout&&<Checkout product={checkout} buyer={buyer} close={()=>setCheckout(null)} place={placeOrder}/>}</div>;
}

function BuyerSetup({buyer,setBuyer,next,loading}){
  const select=x=>setBuyer(prev=>({...prev,preference:x}));
  const phone=e=>setBuyer(prev=>({...prev,phone:e.target.value.replace(/\D/g,'').slice(0,10)}));
  const ready=buyer.name.trim()&&buyer.phone.length===10&&buyer.address.trim()&&buyer.budget&&buyer.preference.trim();
  return <section className="workspace-panel"><span className="eyebrow">✦ PERSONALIZED DISCOVERY</span><h1>Tell us a little about you.</h1><p className="workspace-intro">Enter your details, choose a budget and choose one art preference or type what you want. AI suggestions come next.</p><div className="seller-form"><div className="form-grid"><label>Your name<input value={buyer.name} onChange={e=>setBuyer(prev=>({...prev,name:e.target.value}))}/></label><label>Contact phone<input type="tel" inputMode="numeric" maxLength="10" pattern="[0-9]{10}" placeholder="10-digit mobile number" value={buyer.phone} onChange={phone}/><small>{buyer.phone.length}/10 digits</small></label><label>Delivery address<textarea rows="3" value={buyer.address} onChange={e=>setBuyer(prev=>({...prev,address:e.target.value}))}/></label><label>Budget range<select value={buyer.budget} onChange={e=>setBuyer(prev=>({...prev,budget:e.target.value}))}><option value="">Choose your budget</option>{budgets.map(x=><option key={x}>{x}</option>)}</select></label></div><label>What are you looking for?<input value={buyer.preference} onChange={e=>setBuyer(prev=>({...prev,preference:e.target.value}))} placeholder="e.g. Madhubani painting, pottery, jewellery..."/></label><div className="buyer-craft-options" style={{display:'flex',flexWrap:'wrap',gap:10}}>{buyerInterests.map(x=>{const selected=buyer.preference===x;return <button type="button" key={x} aria-pressed={selected} onClick={()=>select(x)} style={{padding:'10px 14px',borderRadius:999,border:`1px solid ${selected?'var(--rust)':'var(--sand)'}`,background:selected?'var(--rust)':'var(--cream)',color:selected?'var(--ivory)':'var(--brown)',fontWeight:700}}>{selected?'✓ ':''}{x}</button>})}</div><button className="btn primary" onClick={next} disabled={!ready||loading}>{loading?'Creating AI suggestions…':'Next — Get AI suggestions →'}</button></div></section>
}

function BuyerShop({recommendations,buy}){return <section className="workspace-panel"><span className="eyebrow">✦ AI MATCH</span><h1>AI suggested for you.</h1><p className="workspace-intro">Recommendations based on your buyer details, budget and selected interest.</p><div className="buyer-products">{recommendations.map((m,i)=>{const p=m.product||{};return <article key={(p.title||'art')+i}><div className={'product i'+(i%4)}></div><div className="buyer-product-info"><small>{p.craft||'Artwork'} · {p.location||'India'}</small><b>{p.title||'Artwork'}</b><strong>{p.price||'Price on request'}</strong><small>{m.match_percentage||90}% match</small><p>{m.reason||''}</p><button className="btn primary" onClick={()=>buy(p)}>Buy now →</button></div></article>})}</div></section>}

function Checkout({product,buyer,close,place}){const[payment,setPayment]=useState('UPI');const[done,setDone]=useState(false);if(done)return <div className="modal-backdrop"><div className="login-modal"><button className="modal-close" onClick={close}>×</button><span className="eyebrow">ORDER CONFIRMED</span><h2>Order placed successfully!</h2><p>This is a hackathon demo checkout. No real payment was charged.</p><button className="btn primary" onClick={close}>Continue shopping</button></div></div>;return <div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&close()}><div className="login-modal"><button className="modal-close" onClick={close}>×</button><span className="eyebrow">CHECKOUT</span><h2>{product.title||'Artwork'}</h2><p><b>{product.price||'Price on request'}</b></p><p><b>Deliver to</b><br/>{buyer.name}<br/>{buyer.phone}<br/>{buyer.address}</p><label>Choose payment method<select value={payment} onChange={e=>setPayment(e.target.value)}><option>UPI</option><option>Card</option><option>Cash on Delivery</option></select></label>{payment==='UPI'&&<label>UPI ID<input placeholder="name@upi"/></label>}{payment==='Card'&&<label>Card number<input placeholder="1234 5678 9012 3456"/></label>}<button className="modal-submit" onClick={()=>{place(product,payment);setDone(true)}}>Place demo order →</button></div></div>}

function SellerProfile({profile,setProfile,save}){const field=(key,label,placeholder,type='text')=><label>{label}<input type={type} value={profile[key]} onChange={e=>setProfile({...profile,[key]:e.target.value})} placeholder={placeholder} required={['name','craft','location','phone'].includes(key)}/></label>;return <section className="workspace-panel"><span className="eyebrow">SELLER PROFILE</span><h1>Tell buyers about your craft.</h1><p className="workspace-intro">Create the profile buyers will see. Keep cultural, material and origin details in your own words.</p><form className="seller-form" onSubmit={save}><div className="form-grid">{field('name','Artist / artisan name','Your name')}{field('phone','Contact phone','Phone number','tel')}{field('craft','Primary art form','Madhubani, weaving, pottery…')}{field('location','Location','Village / city, state')}{field('price','Typical price range','₹2,000 – ₹8,000')}{field('materials','Materials','Cotton, clay, metal…')}</div><label>About your work<textarea value={profile.bio} onChange={e=>setProfile({...profile,bio:e.target.value})} rows="4"/></label><label>Your story<textarea value={profile.story} onChange={e=>setProfile({...profile,story:e.target.value})} rows="4"/></label><button className="btn primary">Save seller profile →</button></form></section>}

function AddArtwork({image,setImage,addArtwork}){return <section className="workspace-panel"><span className="eyebrow">ADD ARTWORK</span><h1>Put your work in the marketplace.</h1><form className="seller-form" onSubmit={addArtwork}><label className="artwork-upload"><input type="file" accept="image/*" onChange={e=>setImage(e.target.files[0])}/>{image?<strong>{image.name}</strong>:<strong>＋ Add artwork photo</strong>}</label><div className="form-grid"><label>Artwork title<input name="title" required/></label><label>Price<input name="price" placeholder="₹4,500" required/></label><label>Craft / art form<input name="craft"/></label><label>Materials<input name="materials"/></label></div><label>Description<textarea name="description" rows="5"/></label><button className="btn primary">Publish artwork →</button></form></section>}

function SellerHome({profile,artworks,orders,setScreen}){const earnings=orders.reduce((s,o)=>s+Number(String(o.price||'').replace(/[^0-9]/g,'')),0);return <section className="workspace-panel"><div className="workspace-heading"><div><span className="eyebrow">SELLER OVERVIEW</span><h1>{profile.name||'Your creator studio'}</h1><p>{profile.craft?`${profile.craft} · ${profile.location}`:'Complete your profile to start showcasing your work.'}</p></div><button className="btn primary" onClick={()=>setScreen('add')}>＋ Add artwork</button></div><div className="seller-stats"><div><strong>{artworks.length}</strong><span>Published works</span></div><div><strong>{orders.length}</strong><span>Buyer orders</span></div><div><strong>₹{earnings.toLocaleString('en-IN')}</strong><span>Demo earnings</span></div></div><div className="seller-empty">{orders.length?<div className="opportunity-list">{orders.slice().reverse().map(o=><article key={o.id}><div><b>{o.title}</b><small>{o.buyer?.name} · {o.payment}</small></div><strong>{o.price}</strong><button>{o.status}</button></article>)}</div>:<><span className="empty-icon">✦</span><h2>No buyer orders yet.</h2><p>Orders placed through the demo checkout will appear here.</p></>}</div></section>}

function SellerOpportunities({profile}){return <section className="workspace-panel"><span className="eyebrow">AI MARKET LINKAGE</span><h1>Find new opportunities.</h1><p className="workspace-intro">Suggestions use your profile context: {profile.craft||'your craft'} · {profile.location||'your location'}.</p><div className="opportunity-list">{[['Boutique craft stores','Handmade home objects','92% fit'],['Museum shop collections','Story-led Indian craft','86% fit'],['Independent design buyers','Contemporary craft','81% fit']].map(x=><article key={x[0]}><div><b>{x[0]}</b><small>{x[1]}</small></div><strong>{x[2]}</strong><button>Review →</button></article>)}</div></section>}

function BuyerSaved(){return <section className="workspace-panel"><span className="eyebrow">SAVED PIECES</span><h1>Your collection starts here.</h1><div className="empty-large">♡<h2>No saved pieces yet</h2></div></section>}
function BuyerArtists(){return <section className="workspace-panel"><span className="eyebrow">ARTISANS</span><h1>Meet the makers.</h1><div className="artist-list">{[['Meera Devi','Madhubani · Bihar'],['Raghav Sahu','Dhokra · Chhattisgarh'],['Ananya Rao','Weaving · Telangana']].map(x=><article key={x[0]}><div className="portrait">✦</div><div><b>{x[0]}</b><small>{x[1]}</small></div></article>)}</div></section>}
function BuyerOrders({orders}){return <section className="workspace-panel"><span className="eyebrow">ORDERS</span><h1>Your orders.</h1>{orders.length?<div className="opportunity-list">{orders.slice().reverse().map(o=><article key={o.id}><div><b>{o.title}</b><small>{o.payment}</small></div><strong>{o.price}</strong><button>{o.status}</button></article>)}</div>:<div className="empty-large">◌<h2>No orders yet</h2></div>}</section>}

createRoot(document.getElementById('root')).render(<App/>);
