const incomeCopy={
 en:{nav:'Income',ey:'SELLER INCOME',title:'Your earnings at a glance.',sub:'Track the value of demo orders, payment methods and recent sales.',sales:'Demo sales value',orders:'Orders',digital:'Digital payments',cod:'COD pending',recent:'Recent transactions',empty:'No orders yet. Buyer demo orders will appear here.',buyer:'Buyer',item:'Artwork',payment:'Payment',amount:'Amount',status:'Status',note:'Hackathon demo: these figures come from demo orders. No real money is transferred.',download:'Download statement'},
 hi:{nav:'आय',ey:'विक्रेता आय',title:'अपनी कमाई एक नज़र में देखें।',sub:'डेमो ऑर्डर का मूल्य, भुगतान के तरीके और हाल की बिक्री देखें।',sales:'डेमो बिक्री मूल्य',orders:'ऑर्डर',digital:'डिजिटल भुगतान',cod:'COD लंबित',recent:'हाल के लेन-देन',empty:'अभी कोई ऑर्डर नहीं है। खरीदार के डेमो ऑर्डर यहाँ दिखेंगे।',buyer:'खरीदार',item:'कलाकृति',payment:'भुगतान',amount:'राशि',status:'स्थिति',note:'हैकाथॉन डेमो: ये आँकड़े डेमो ऑर्डर से आते हैं। कोई वास्तविक धन हस्तांतरण नहीं होता।',download:'स्टेटमेंट डाउनलोड करें'},
 bn:{nav:'আয়',ey:'বিক্রেতার আয়',title:'এক নজরে আপনার আয় দেখুন।',sub:'ডেমো অর্ডারের মূল্য, পেমেন্ট পদ্ধতি ও সাম্প্রতিক বিক্রি দেখুন।',sales:'ডেমো বিক্রির মূল্য',orders:'অর্ডার',digital:'ডিজিটাল পেমেন্ট',cod:'COD বাকি',recent:'সাম্প্রতিক লেনদেন',empty:'এখনও কোনো অর্ডার নেই। ক্রেতার ডেমো অর্ডার এখানে দেখা যাবে।',buyer:'ক্রেতা',item:'শিল্পকর্ম',payment:'পেমেন্ট',amount:'পরিমাণ',status:'অবস্থা',note:'হ্যাকাথন ডেমো: এই সংখ্যা ডেমো অর্ডার থেকে আসে। কোনো আসল অর্থ স্থানান্তর হয় না।',download:'স্টেটমেন্ট ডাউনলোড করুন'},
 mr:{nav:'उत्पन्न',ey:'विक्रेता उत्पन्न',title:'तुमची कमाई एका नजरेत.',sub:'डेमो ऑर्डरचे मूल्य, पेमेंट पद्धती आणि अलीकडील विक्री पहा.',sales:'डेमो विक्री मूल्य',orders:'ऑर्डर',digital:'डिजिटल पेमेंट',cod:'COD प्रलंबित',recent:'अलीकडील व्यवहार',empty:'अजून ऑर्डर नाहीत. खरेदीदारांचे डेमो ऑर्डर येथे दिसतील.',buyer:'खरेदीदार',item:'कलाकृती',payment:'पेमेंट',amount:'रक्कम',status:'स्थिती',note:'हॅकाथॉन डेमो: हे आकडे डेमो ऑर्डरमधून येतात. प्रत्यक्ष पैसे हस्तांतरित होत नाहीत.',download:'स्टेटमेंट डाउनलोड करा'},
 gu:{nav:'આવક',ey:'વિક્રેતા આવક',title:'તમારી કમાણી એક નજરમાં.',sub:'ડેમો ઓર્ડરનું મૂલ્ય, ચુકવણી પદ્ધતિ અને તાજેતરની વેચાણ જુઓ.',sales:'ડેમો વેચાણ મૂલ્ય',orders:'ઓર્ડર',digital:'ડિજિટલ ચુકવણી',cod:'COD બાકી',recent:'તાજેતરના વ્યવહારો',empty:'હજુ કોઈ ઓર્ડર નથી. ખરીદદારના ડેમો ઓર્ડર અહીં દેખાશે.',buyer:'ખરીદદાર',item:'કલાત્મક વસ્તુ',payment:'ચુકવણી',amount:'રકમ',status:'સ્થિતિ',note:'હેકાથોન ડેમો: આ આંકડા ડેમો ઓર્ડરમાંથી આવે છે. વાસ્તવિક પૈસા ટ્રાન્સફર થતા નથી.',download:'સ્ટેટમેન્ટ ડાઉનલોડ કરો'},
 ta:{nav:'வருமானம்',ey:'விற்பனையாளர் வருமானம்',title:'உங்கள் வருமானத்தை ஒரே பார்வையில் காணுங்கள்.',sub:'டெமோ ஆர்டர்களின் மதிப்பு, கட்டண முறைகள் மற்றும் சமீப விற்பனைகளைப் பாருங்கள்.',sales:'டெமோ விற்பனை மதிப்பு',orders:'ஆர்டர்கள்',digital:'டிஜிட்டல் கட்டணம்',cod:'COD நிலுவை',recent:'சமீப பரிவர்த்தனைகள்',empty:'இன்னும் ஆர்டர்கள் இல்லை. வாங்குபவர் டெமோ ஆர்டர்கள் இங்கே தோன்றும்.',buyer:'வாங்குபவர்',item:'கலைப்பணி',payment:'கட்டணம்',amount:'தொகை',status:'நிலை',note:'ஹேக்கத்தான் டெமோ: இந்த மதிப்புகள் டெமோ ஆர்டர்களிலிருந்து வருகின்றன. உண்மையான பண பரிமாற்றம் இல்லை.',download:'அறிக்கையை பதிவிறக்கவும்'},
 te:{nav:'ఆదాయం',ey:'విక్రేత ఆదాయం',title:'మీ ఆదాయాన్ని ఒక చూపులో చూడండి.',sub:'డెమో ఆర్డర్ విలువ, చెల్లింపు విధానాలు మరియు తాజా అమ్మకాలను చూడండి.',sales:'డెమో అమ్మకాల విలువ',orders:'ఆర్డర్లు',digital:'డిజిటల్ చెల్లింపులు',cod:'COD పెండింగ్',recent:'తాజా లావాదేవీలు',empty:'ఇంకా ఆర్డర్లు లేవు. కొనుగోలుదారుల డెమో ఆర్డర్లు ఇక్కడ కనిపిస్తాయి.',buyer:'కొనుగోలుదారు',item:'కళాఖండం',payment:'చెల్లింపు',amount:'మొత్తం',status:'స్థితి',note:'హ్యాకథాన్ డెమో: ఈ గణాంకాలు డెమో ఆర్డర్ల నుండి వస్తాయి. నిజమైన డబ్బు బదిలీ జరగదు.',download:'స్టేట్మెంట్ డౌన్‌లోడ్ చేయండి'},
 kn:{nav:'ಆದಾಯ',ey:'ಮಾರಾಟಗಾರರ ಆದಾಯ',title:'ನಿಮ್ಮ ಆದಾಯವನ್ನು ಒಂದೇ ನೋಟದಲ್ಲಿ ನೋಡಿ.',sub:'ಡೆಮೊ ಆರ್ಡರ್ ಮೌಲ್ಯ, ಪಾವತಿ ವಿಧಾನಗಳು ಮತ್ತು ಇತ್ತೀಚಿನ ಮಾರಾಟಗಳನ್ನು ನೋಡಿ.',sales:'ಡೆಮೊ ಮಾರಾಟ ಮೌಲ್ಯ',orders:'ಆರ್ಡರ್‌ಗಳು',digital:'ಡಿಜಿಟಲ್ ಪಾವತಿಗಳು',cod:'COD ಬಾಕಿ',recent:'ಇತ್ತೀಚಿನ ವ್ಯವಹಾರಗಳು',empty:'ಇನ್ನೂ ಆರ್ಡರ್‌ಗಳಿಲ್ಲ. ಖರೀದಿದಾರರ ಡೆಮೊ ಆರ್ಡರ್‌ಗಳು ಇಲ್ಲಿ ಕಾಣುತ್ತವೆ.',buyer:'ಖರೀದಿದಾರ',item:'ಕಲಾಕೃತಿ',payment:'ಪಾವತಿ',amount:'ಮೊತ್ತ',status:'ಸ್ಥಿತಿ',note:'ಹ್ಯಾಕಥಾನ್ ಡೆಮೊ: ಈ ಅಂಕಿಗಳು ಡೆಮೊ ಆರ್ಡರ್‌ಗಳಿಂದ ಬರುತ್ತವೆ. ನಿಜವಾದ ಹಣ ವರ್ಗಾವಣೆ ಆಗುವುದಿಲ್ಲ.',download:'ಸ್ಟೇಟ್ಮೆಂಟ್ ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ'},
 ml:{nav:'വരുമാനം',ey:'വിൽപ്പനക്കാരന്റെ വരുമാനം',title:'നിങ്ങളുടെ വരുമാനം ഒറ്റനോട്ടത്തിൽ.',sub:'ഡെമോ ഓർഡർ മൂല്യം, പേയ്മെന്റ് രീതികൾ, പുതിയ വിൽപ്പനകൾ എന്നിവ കാണുക.',sales:'ഡെമോ വിൽപ്പന മൂല്യം',orders:'ഓർഡറുകൾ',digital:'ഡിജിറ്റൽ പേയ്മെന്റുകൾ',cod:'COD ബാക്കി',recent:'പുതിയ ഇടപാടുകൾ',empty:'ഇനിയും ഓർഡറുകളില്ല. വാങ്ങുന്നവരുടെ ഡെമോ ഓർഡറുകൾ ഇവിടെ കാണും.',buyer:'വാങ്ങുന്നവർ',item:'കലാസൃഷ്ടി',payment:'പേയ്മെന്റ്',amount:'തുക',status:'നില',note:'ഹാക്കത്തോൺ ഡെമോ: ഈ കണക്കുകൾ ഡെമോ ഓർഡറുകളിൽ നിന്നുള്ളതാണ്. യഥാർത്ഥ പണം കൈമാറുന്നില്ല.',download:'സ്റ്റേറ്റ്മെന്റ് ഡൗൺലോഡ് ചെയ്യുക'},
 or:{nav:'ଆୟ',ey:'ବିକ୍ରେତା ଆୟ',title:'ଆପଣଙ୍କ ଆୟକୁ ଏକ ନଜରରେ ଦେଖନ୍ତୁ।',sub:'ଡେମୋ ଅର୍ଡର ମୂଲ୍ୟ, ପେମେଣ୍ଟ ପ୍ରକାର ଓ ସମ୍ପ୍ରତିକ ବିକ୍ରି ଦେଖନ୍ତୁ।',sales:'ଡେମୋ ବିକ୍ରି ମୂଲ୍ୟ',orders:'ଅର୍ଡର',digital:'ଡିଜିଟାଲ ପେମେଣ୍ଟ',cod:'COD ବକେୟା',recent:'ସମ୍ପ୍ରତିକ ଲେନଦେନ',empty:'ଏପର୍ଯ୍ୟନ୍ତ କୌଣସି ଅର୍ଡର ନାହିଁ। କ୍ରେତାଙ୍କ ଡେମୋ ଅର୍ଡର ଏଠାରେ ଦେଖାଯିବ।',buyer:'କ୍ରେତା',item:'କଳାକୃତି',payment:'ପେମେଣ୍ଟ',amount:'ରାଶି',status:'ସ୍ଥିତି',note:'ହ୍ୟାକାଥନ ଡେମୋ: ଏହି ଆକଡା ଡେମୋ ଅର୍ଡରରୁ ଆସେ। ପ୍ରକୃତ ଟଙ୍କା ଟ୍ରାନ୍ସଫର ହୁଏ ନାହିଁ।',download:'ଷ୍ଟେଟମେଣ୍ଟ ଡାଉନଲୋଡ୍ କରନ୍ତୁ'},
 pa:{nav:'ਆਮਦਨ',ey:'ਵਿਕਰੇਤਾ ਆਮਦਨ',title:'ਆਪਣੀ ਕਮਾਈ ਇੱਕ ਨਜ਼ਰ ਵਿੱਚ ਵੇਖੋ।',sub:'ਡੈਮੋ ਆਰਡਰ ਦੀ ਕੀਮਤ, ਭੁਗਤਾਨ ਢੰਗ ਅਤੇ ਹਾਲੀਆ ਵਿਕਰੀ ਵੇਖੋ।',sales:'ਡੈਮੋ ਵਿਕਰੀ ਮੁੱਲ',orders:'ਆਰਡਰ',digital:'ਡਿਜਿਟਲ ਭੁਗਤਾਨ',cod:'COD ਬਾਕੀ',recent:'ਹਾਲੀਆ ਲੈਣ-ਦੇਣ',empty:'ਹਾਲੇ ਕੋਈ ਆਰਡਰ ਨਹੀਂ। ਖਰੀਦਦਾਰ ਡੈਮੋ ਆਰਡਰ ਇੱਥੇ ਨਜ਼ਰ ਆਉਣਗੇ।',buyer:'ਖਰੀਦਦਾਰ',item:'ਕਲਾ ਕਿਰਤੀ',payment:'ਭੁਗਤਾਨ',amount:'ਰਕਮ',status:'ਸਥਿਤੀ',note:'ਹੈਕਾਥਾਨ ਡੈਮੋ: ਇਹ ਅੰਕ ਡੈਮੋ ਆਰਡਰਾਂ ਤੋਂ ਹਨ। ਕੋਈ ਅਸਲ ਪੈਸਾ ਟ੍ਰਾਂਸਫਰ ਨਹੀਂ ਹੁੰਦਾ।',download:'ਸਟੇਟਮੈਂਟ ਡਾਊਨਲੋਡ ਕਰੋ'},
 as:{nav:'আয়',ey:'বিক্ৰেতাৰ আয়',title:'আপোনাৰ উপাৰ্জন একে নজৰত চাওক।',sub:'ডেমো অৰ্ডাৰৰ মূল্য, পেমেণ্ট পদ্ধতি আৰু সাম্প্ৰতিক বিক্ৰী চাওক।',sales:'ডেমো বিক্ৰীৰ মূল্য',orders:'অৰ্ডাৰ',digital:'ডিজিটেল পেমেণ্ট',cod:'COD বাকী',recent:'সাম্প্ৰতিক লেনদেন',empty:'এতিয়াও কোনো অৰ্ডাৰ নাই। ক্ৰেতাৰ ডেমো অৰ্ডাৰ ইয়াত দেখা যাব।',buyer:'ক্ৰেতা',item:'শিল্পকর্ম',payment:'পেমেণ্ট',amount:'পৰিমাণ',status:'স্থিতি',note:'হেকাথন ডেমো: এই সংখ্যাবোৰ ডেমো অৰ্ডাৰৰ পৰা আহে। কোনো বাস্তৱ ধন স্থানান্তৰ নহয়।',download:'ষ্টেটমেণ্ট ডাউনলোড কৰক'}
};

const money=v=>Number(String(v||'').replace(/[^0-9]/g,''))||0;
const rupees=n=>'₹'+Number(n||0).toLocaleString('en-IN');
const orders=()=>{try{return JSON.parse(localStorage.getItem('ac-demo-orders')||'[]')}catch{return[]}};
const lang=()=>localStorage.getItem('ac-lang')||'en';

function downloadStatement(list,t){
 const rows=[[t.item,t.buyer,t.payment,t.amount,t.status],...list.map(o=>[o.title||'',o.buyer?.name||'',o.payment||'',o.price||'',o.status||'New'])];
 const csv=rows.map(r=>r.map(v=>'"'+String(v).replace(/"/g,'""')+'"').join(',')).join('\n');
 const blob=new Blob([csv],{type:'text/csv;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='artisan-connect-income.csv';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);
}

function renderIncome(){
 const content=document.querySelector('.dashboard-content');if(!content)return;
 const list=orders();const t=incomeCopy[lang()]||incomeCopy.en;
 const total=list.reduce((s,o)=>s+money(o.price),0);
 const digital=list.filter(o=>o.payment!=='Cash on Delivery').reduce((s,o)=>s+money(o.price),0);
 const cod=list.filter(o=>o.payment==='Cash on Delivery').reduce((s,o)=>s+money(o.price),0);
 document.querySelectorAll('.dashboard-sidebar button').forEach(b=>b.classList.remove('active'));
 document.querySelector('#ac-income-nav')?.classList.add('active');
 content.innerHTML=`<section class="workspace-panel ac-income-panel"><div class="workspace-heading"><div><span class="eyebrow">${t.ey}</span><h1>${t.title}</h1><p>${t.sub}</p></div><button class="btn secondary" id="ac-income-download">↓ ${t.download}</button></div><div class="ac-income-cards"><article><small>${t.sales}</small><strong>${rupees(total)}</strong><span>↗ ${list.length} ${t.orders.toLowerCase()}</span></article><article><small>${t.orders}</small><strong>${list.length}</strong><span>◎ ${t.recent}</span></article><article><small>${t.digital}</small><strong>${rupees(digital)}</strong><span>UPI / Card</span></article><article><small>${t.cod}</small><strong>${rupees(cod)}</strong><span>Cash on Delivery</span></article></div><div class="ac-income-note">ⓘ ${t.note}</div><div class="ac-income-list"><h2>${t.recent}</h2>${list.length?`<div class="ac-income-table"><div class="ac-income-row head"><span>${t.item}</span><span>${t.buyer}</span><span>${t.payment}</span><span>${t.amount}</span><span>${t.status}</span></div>${list.slice().reverse().map(o=>`<div class="ac-income-row"><span><b>${o.title||'Artwork'}</b><small>${o.craft||''}</small></span><span>${o.buyer?.name||'—'}</span><span>${o.payment||'—'}</span><span><b>${o.price||'—'}</b></span><span><em>${o.status||'New'}</em></span></div>`).join('')}</div>`:`<div class="empty-large">₹<h2>${t.empty}</h2></div>`}</div></section>`;
 content.querySelector('#ac-income-download')?.addEventListener('click',()=>downloadStatement(list,t));
}

function installIncome(){
 if(localStorage.getItem('ac-user-role')!=='artisan')return;
 const side=document.querySelector('.dashboard-sidebar');if(!side||side.querySelector('#ac-income-nav'))return;
 const logout=side.querySelector('.sidebar-logout');
 const b=document.createElement('button');b.id='ac-income-nav';b.innerHTML=`${(incomeCopy[lang()]||incomeCopy.en).nav} <span>→</span>`;b.addEventListener('click',renderIncome);
 side.insertBefore(b,logout||null);
}

const style=document.createElement('style');style.textContent=`
.ac-income-cards{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:14px;margin:24px 0}.ac-income-cards article{padding:20px;border:1px solid rgba(92,53,33,.12);border-radius:18px;background:#fffaf2;display:flex;flex-direction:column;gap:7px}.ac-income-cards small{font-size:12px;text-transform:uppercase;letter-spacing:.08em;opacity:.65}.ac-income-cards strong{font-family:Georgia,serif;font-size:30px;color:var(--espresso)}.ac-income-cards span{font-size:12px;color:var(--rust);font-weight:700}.ac-income-note{padding:13px 15px;border-left:3px solid var(--rust);border-radius:10px;background:rgba(188,82,43,.07);font-size:13px;margin-bottom:24px}.ac-income-list h2{margin-bottom:12px}.ac-income-table{border:1px solid rgba(92,53,33,.12);border-radius:16px;overflow:hidden}.ac-income-row{display:grid;grid-template-columns:2fr 1.2fr 1.2fr 1fr .8fr;gap:12px;align-items:center;padding:14px 16px;border-top:1px solid rgba(92,53,33,.1);font-size:13px}.ac-income-row:first-child{border-top:0}.ac-income-row.head{background:rgba(188,82,43,.07);font-weight:800;font-size:11px;text-transform:uppercase;letter-spacing:.06em}.ac-income-row span{min-width:0}.ac-income-row span:first-child{display:flex;flex-direction:column;gap:3px}.ac-income-row small{opacity:.6}.ac-income-row em{font-style:normal;padding:5px 8px;border-radius:999px;background:rgba(188,82,43,.1);color:var(--rust);font-weight:800;font-size:11px}@media(max-width:900px){.ac-income-cards{grid-template-columns:repeat(2,1fr)}.ac-income-row{grid-template-columns:1.6fr 1fr 1fr}.ac-income-row span:nth-child(2),.ac-income-row.head span:nth-child(2){display:none}}@media(max-width:560px){.ac-income-cards{grid-template-columns:1fr}.ac-income-row{grid-template-columns:1.5fr 1fr}.ac-income-row span:nth-child(3),.ac-income-row.head span:nth-child(3){display:none}}
`;document.head.appendChild(style);

new MutationObserver(installIncome).observe(document.body,{childList:true,subtree:true});
installIncome();
